# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='dssdvsvdv'),
            preserve_default=False,
        ),
    ]
